### ISSUE TITLE
multiple setup.sh issues (not existing github repo and no exit code checks)

### ISSUE THREAD

**Issue by Name63** [eris-ltd/common#63] opened 2016-07-21 16:08 UTC
Hi all,

Faced an issue during [cloud-getting-started](https://docs.erisindustries.com/tutorials/advanced/cloud-getting-started) tutorial. Looks like setup.sh is not in a good shape anymore:

github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/archive doesn't exists anymore
setup.sh reports "Eris Installed!" even if build fails. It doesn't check if eris binary was created and not checks "eris init" return value - it just assumes that everything goes smooth and

Full output attached below, see **bold** lines:
> \# curl -sSL --ssl-req https://raw.githubusercontent.com/eris-ltd/common/master/cloud/setup/setup.sh | bash
> Hello there! I'm the marmot that installs Eris.
>  
>  
> Grabbing necessary dependencies
> Dependencies Installed.
>  
>  
> Getting Chain managers
> Chain managers acquired.
>  
>  
> Setting up Go for the user
> Finished Setting up Go.
>  
>  
> Version Information
>  
> go version go1.5 linux/amd64
>  
> Client:
>  Version:      1.11.2
>  API version:  1.23
>  Go version:   go1.5.4
>  Git commit:   b9f10c9
>  Built:        Wed Jun  1 21:47:50 2016
>  OS/Arch:      linux/amd64
>  
> Server:
>  Version:      1.11.2
>  API version:  1.23
>  Go version:   go1.5.4
>  Git commit:   b9f10c9
>  Built:        Wed Jun  1 21:47:50 2016
>  OS/Arch:      linux/amd64
>  
>  
> Building eris.
> **package github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/archive: cannot find package "github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/archive" in any of:**
>         **/usr/local/go/src/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/archive (from $GOROOT)**
>         **/root/go/src/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/archive (from $GOPATH)**
>  
>  
> Initializing eris.
>  
>  
> Starting Services and Chains:
>  
> No services or chains selected
>  
> Finished starting services and chains.
>  
>  
> **Eris Installed!**

**Comment by pietv** [comment] 2016-07-21 18:38
Hi @Name63, thank you for reporting the issue! The problem is that the `github.com/eris-ltd/eris-cli` project is using the `/vendor`ing technique which is supported in Go version 1.5 only with the `GO15VENDOREXPERIMENT` variable and that the shell commands don't catch some error cases as you've pointed out. I'll implement a fix to this script, test, and chat you back. Thanks!

**Comment by Name63** [comment] 2016-07-21 19:04
well, at least you could add something like 
if ! [ -f $path_to_eris_binary ]; then; echo 'error'; exit 1; fi

**Comment by pietv** [comment] 2016-07-21 19:43
@Name63 you can try repeating your experiment with running the cloud `setup.sh` at your leisure.

**Comment by pietv** [comment] 2016-07-26 00:13
Closing. Please, feel free to reopen if you have further issues.

**Closed by pietv** 2016-07-26 00:13 UTC
Labels: bug

**Comment by Name63** [comment] 2016-07-26 06:59
@pietv tested it, works fine now.
